### ISSUE TITLE
mr esap not deployed 

### ISSUE THREAD

**Issue by volodymyrss** [cta-epfl/mr-controller#1]
https://gitlab.cta-observatory.org/cta-computing/suss/sdc-portal/prototypes/ctao-esap-sdc-portal/-/merge_requests/8

**Comment by Ph0tonic** [comment]
Fixed with :
- https://github.com/cta-epfl/mr-controller/compare/b4d4731772445185d286bb159dd5c6c6fcaa34a5...5af342eca5f84b7e3270e509be5b921ef6374f98

And flux-jh adapted:
- https://github.com/cta-epfl/flux-jh/commit/5b3046b9c67bd6ac59ed83ccec25a957b57c6661
